# Generated by Django 4.2.4 on 2023-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_user_bio_user_name_alter_user_email_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackathon_particpant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
